/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package my_demo_app;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.util.ArrayList;
import java.util.Arrays;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    @Test
    public void testFound() {
      ArrayList<Integer> array = new ArrayList<>(Arrays.asList(4, 2, 10, 2,  3, 20, 12, 7,9));
      assertTrue(App.checkSubarraySum(array, 4, 18));
    }

    @Test
    public void testNotFoundForSmallerK() {
        ArrayList<Integer> array = new ArrayList<>(Arrays.asList(4, 2, 10, 2,  3, 20, 12, 7,9));
        assertFalse(App.search_pow(array, 3, 18));
    }

    @Test
    public void testNotFoundForBiggerK() {
        ArrayList<Integer> array = new ArrayList<>(Arrays.asList(4, 2, 10, 2,  3, 20, 12, 7,9));
        assertFalse(App.search_pow(array, 5, 18));
    }

    @Test
    public void testFoundForBiggerKWhenAddZero() {
        ArrayList<Integer> array = new ArrayList<>(Arrays.asList(0, 4, 2, 10, 2,  3, 20, 12, 7,9));
        assertTrue(App.search_pow(array, 5, 18));
    }  

    @Test
    public void testEmptyArray() {
      ArrayList<Integer> array = new ArrayList<>();
      assertFalse(App.search_pow(array, 2, 5));
    }

    @Test
    public void testNull() {
      assertFalse(App.search_pow(null, 4, 5));
    }

}
